import {
  agentTasks,
  agentWorkspaces,
  chatMessages,
  createDb,
  toolRequests
} from "@agentcompany/db";
import { and, eq } from "drizzle-orm";
import path from "node:path";
import { threadWorkspaceDir, writeTextFile } from "@/lib/local-storage";

function titleFromGoal(goal: string) {
  const cleaned = goal.replace(/\s+/g, " ").trim();
  return (cleaned.length > 48 ? cleaned.slice(0, 45) + "..." : cleaned) || "New workspace";
}

function shouldRequestCommand(goal: string) {
  return /\b(npm|docker|test|build|run|terminal|command|shell|install)\b/i.test(goal);
}

export async function runLocalAgentWorkflow(input: {
  tenantId: string;
  threadId: string;
  userMessage: string;
}) {
  const db = createDb();
  const workspaceName = titleFromGoal(input.userMessage);
  const localPath = threadWorkspaceDir(input.threadId);
  const now = new Date();

  const [existingWorkspace] = await db
    .select()
    .from(agentWorkspaces)
    .where(and(eq(agentWorkspaces.threadId, input.threadId), eq(agentWorkspaces.status, "active")))
    .limit(1);

  const workspace =
    existingWorkspace ||
    (
      await db
        .insert(agentWorkspaces)
        .values({
          tenantId: input.tenantId,
          threadId: input.threadId,
          name: workspaceName,
          status: "active",
          summary: input.userMessage,
          localPath
        })
        .returning()
    )[0];

  await db
    .update(agentWorkspaces)
    .set({
      name: workspaceName,
      summary: input.userMessage,
      updatedAt: now
    })
    .where(eq(agentWorkspaces.id, workspace.id));

  const tasks = [
    {
      workerId: "manager_product",
      description: "Clarify the user goal and split it into an implementation plan.",
      status: "done",
      result: "Goal analyzed and converted into a workspace plan."
    },
    {
      workerId: "worker_builder",
      description: "Create starter project files in the workspace.",
      status: "done",
      result: "README, task list, and handover files were written."
    },
    {
      workerId: "worker_reviewer",
      description: "Check the result and list the next safe actions.",
      status: "done",
      result: "Workspace is ready for review. Hosted server commands remain disabled by default."
    }
  ];

  await Promise.all(
    tasks.map((task) =>
      db.insert(agentTasks).values({
        tenantId: input.tenantId,
        threadId: input.threadId,
        workspaceId: workspace.id,
        ...task
      })
    )
  );

  await writeTextFile(
    path.join(localPath, "README.md"),
    `# ${workspaceName}\n\n## User Goal\n\n${input.userMessage}\n\n## Status\n\nGenerated by AgentCompany agent workflow.\n`
  );
  await writeTextFile(
    path.join(localPath, "TASKS.md"),
    tasks.map((task) => `- [x] **${task.workerId}**: ${task.description}\n  - ${task.result}`).join("\n")
  );
  await writeTextFile(
    path.join(localPath, "HANDOVER.md"),
    `# Handover\n\nWorkspace: ${workspaceName}\n\nNext step: review the generated files and approve any requested commands if needed.\n`
  );

  const messages = [
    {
      role: "assistant",
      authorName: "CEO",
      content: `I created a workspace for this goal: "${workspaceName}".`
    },
    {
      role: "assistant",
      authorName: "Manager",
      content: "I split the work into planning, implementation, and review tasks."
    },
    {
      role: "assistant",
      authorName: "Worker",
      content: "I wrote README.md, TASKS.md, and HANDOVER.md into the chat workspace."
    }
  ];

  await db.insert(chatMessages).values(
    messages.map((message) => ({
      tenantId: input.tenantId,
      threadId: input.threadId,
      ...message
    }))
  );

  if (shouldRequestCommand(input.userMessage) && process.env.ENABLE_SERVER_COMMANDS === "true") {
    await db.insert(toolRequests).values({
      tenantId: input.tenantId,
      threadId: input.threadId,
      toolName: "terminal",
      reason: "The workflow mentions running or testing commands. User approval is required before executing anything.",
      status: "pending",
      payload: {
        command: "npm run smoke",
        cwd: process.cwd(),
        stdout: "",
        stderr: "",
        exit_code: null
      }
    });
  } else if (shouldRequestCommand(input.userMessage)) {
    await db.insert(chatMessages).values({
      tenantId: input.tenantId,
      threadId: input.threadId,
      role: "assistant",
      authorName: "System",
      content:
        "Hosted server command execution is disabled, so I prepared the workspace without running terminal commands."
    });
  }

  return { workspace };
}
